AddLocationForm:

<AddLocationForm>:  # 1
    orientation: "vertical"
    search_input: search_box
    BoxLayout:
        height: "40dp"
        size_hint_y: None
        TextInput:
            id: search_box
            size_hint_x: 50
        Button:
            text: "Search"
            size_hint_x: 25
            on_press: root.search_location()
        Button:
            text: "Current Location"
            size_hint_x: 25
    RecycleView:
        item_strings: ["Palo Alto, MX", "Palo Alto, US"]